CREATE TABLE encounters_raw (
    `Id` VARCHAR(36),
    `START` VARCHAR(30),
    `STOP` VARCHAR(30),
    `PATIENT` VARCHAR(36),
    `ORGANIZATION` VARCHAR(36),
    `PAYER` VARCHAR(36),
    `ENCOUNTERCLASS` VARCHAR(50),
    `CODE` VARCHAR(30),
    `DESCRIPTION` TEXT,
    `BASE_ENCOUNTER_COST` VARCHAR(30),
    `TOTAL_CLAIM_COST` VARCHAR(30),
    `PAYER_COVERAGE` VARCHAR(30),
    `REASONCODE` VARCHAR(30),
    `REASONDESCRIPTION` TEXT
);

LOAD DATA LOCAL INFILE '/Users/selam/Downloads/Hospital+Patient+Records/encounters.csv'
INTO TABLE encounters_raw
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT 
    START,
    STR_TO_DATE(REPLACE(REPLACE(START, 'T', ' '), 'Z', ''), '%Y-%m-%d %H:%i:%s') AS Start_Converted
FROM encounters_raw;

